<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="testap" tests="5" time="0.000">
  <testsuite name="GetAll" id="2f80b805-7af7-47cb-9ffc-fb11ff33a059" timestamp="2022-02-04T09:16:03.794Z" tests="1" failures="1" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: getaddrinfo EAI_AGAIN testtap
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

---
]]></system-err>
    <testcase name="Status code is 200" time="0.000" classname="Testap">
      <failure type="AssertionFailure" message="expected { Object (id, _details, ...) } to have property 'code'">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 36212799-c2e5-4e93-88dd-47c42293b2ec.]]>
        <![CDATA[Collection name: testap.]]>
        <![CDATA[Request name: GetAll.]]>
        <![CDATA[Test description: Status code is 200.]]>
        <![CDATA[Error message: expected { Object (id, _details, ...) } to have property 'code'.]]>
        <![CDATA[Stacktrace: AssertionError: expected { Object (id, _details, ...) } to have property 'code'
   at Object.eval sandbox-script.js:1:1).]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="PostPerson" id="fc28977a-f496-4790-b0df-14a94f8cf984" timestamp="2022-02-04T09:16:03.794Z" tests="0" failures="0" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: getaddrinfo EAI_AGAIN testtap
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

---
]]></system-err>
  </testsuite>
  <testsuite name="GetById" id="e596c796-474c-4c5f-abe3-72280c450afd" timestamp="2022-02-04T09:16:03.794Z" tests="0" failures="0" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: getaddrinfo EAI_AGAIN testtap
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

---
]]></system-err>
  </testsuite>
  <testsuite name="PutPerson" id="29942b99-8af6-4bc2-89c9-0ae397ce03fe" timestamp="2022-02-04T09:16:03.794Z" tests="0" failures="0" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: getaddrinfo EAI_AGAIN testtap
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

---
]]></system-err>
  </testsuite>
  <testsuite name="DeleteById=1" id="48717b16-15a3-4801-8ab1-352735a9019d" timestamp="2022-02-04T09:16:03.794Z" tests="0" failures="0" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: getaddrinfo EAI_AGAIN testtap
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

---
]]></system-err>
  </testsuite>
</testsuites>